const imposter = require("../dist/index.js");

// console.log(imposter.name());
// console.log(imposter.address());
// console.log(imposter.city());
// console.log(imposter.state());
// console.log(imposter.postalCode());
// console.log(imposter.coordinates());
// console.log(imposter.latitude());
// console.log(imposter.longitude());
// console.log(imposter.loremIpsum());
// console.log(imposter.uuid());
// console.log(imposter.phone());
// console.log(imposter.email());
// console.log(imposter.ip());
// console.log(imposter.macAddress());
// console.log(imposter.url());
// console.log(imposter.randomString());
// console.log(imposter.randomNumber());
// console.log(imposter.randomBoolean());
